eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8011/eureka/
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nsummer/config-test.git
          username: nsummer
          password: xia131871
